### ISSUE TITLE
Checking Record With Multiple Mapping Formats - Error Descriptions 

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wpckan#101]
Alex I was just going through a rich data record testing the elements out:

https://pp-data.opendevelopmentmekong.net/en/dataset/mrs_emission_co2?type=dataset

I hit each resources link: MANAGE WORKED FOR ALL 

HTML
====
VIEW DIDNT SHOW (blank image)
https://pp-data.opendevelopmentmekong.net/en/dataset/mrs_emission_co2/resource/84641606-6f90-4c3f-96eb-0c52e52a10bd?type=dataset

GOT 404 on DOWNLOAD
https://geoserver.opendevelopmentmekong.net/geoserver/Mekong_Regional_Site/wms?service=WMS&version=1.1.0&request=GetMap&layers=Mekong_Regional_Site:MRS_Emission_CO2&styles=&bbox=211430.86563420878,1144585.4696614784,784623.3606298851,1625594.694892376&width=512&height=429&srs=EPSG:32648&format=application/openlayers

KML
===
View Worked

Go to Resource  - 404 Error
https://geoserver.opendevelopmentmekong.net/geoserver/Mekong_Regional_Site/wms?service=WMS&version=1.1.0&request=GetMap&layers=Mekong_Regional_Site:MRS_Emission_CO2&styles=&bbox=211430.86563420878,1144585.4696614784,784623.3606298851,1625594.694892376&width=512&height=429&srs=EPSG:32648&format=application/vnd.google-earth.kml

JSON 
====
View Worked but bunch of proteus errors at top
https://pp-data.opendevelopmentmekong.net/en/dataset/mrs_emission_co2/resource/224cf5cb-af74-4734-8006-3b71e75acf7e?type=dataset

 Could not proxy resource because a connection error occurred. hostname 'geoserver.opendevelopmentmekong.net' doesn't match either of '*.proteus-tech.com', 'proteus-tech.com'
×
Could not proxy resource because a connection error occurred. hostname 'geoserver.opendevelopmentmekong.net' doesn't match either of '*.proteus-tech.com', 'proteus-tech.com'
×
Could not proxy resource because a connection error occurred. hostname 'geoserver.opendevelopmentmekong.net' doesn't match either of '*.proteus-tech.com', 'proteus-tech.com' 

GO TO RESOURCE - Looks like it worked got ccordinates
https://pp-data.opendevelopmentmekong.net/dataset/0029476c-7b1f-4329-8c74-c8eca9cedbe8/resource/224cf5cb-af74-4734-8006-3b71e75acf7e/download/923ab7bb-7081-4a47-8f7b-6636a7ca9ef3.geojson

CSV
===
View Worked
Go to Resource Worked
DATA API Worked

PNG 
===
View Worked
Resource Worked

PDF
===
Worked
Go to resource worked

**Comment by acorbi** [comment]
@jpeizer1 this repository is for the WPCKAN plugin, can you please move (copy/paste) this issue into https://github.com/OpenDevelopmentMekong/ckanext-odm_dataset (general CKAN repo for datasets)

**Comment by jpeizer1** [comment]
https://github.com/OpenDevelopmentMekong/ckanext-odm_dataset/issues/253  DUP -- Closed
