### ISSUE TITLE
Name of the resource disappears.

### ISSUE THREAD

**Issue by punwath** [OpenDevelopmentMekong/wpckan#146]
The name of the resource often disappears. 
![image](https://cloud.githubusercontent.com/assets/18112596/16909075/4e0d2abe-4cfa-11e6-94fe-94da997cbd5c.png)

**Comment by acorbi** [comment]
@punwath can you please provide some links where the issue appears?

**Comment by punwath** [comment]
https://data.opendevelopmentmekong.net/km/dataset/hydropower-reservoirs-in-cambodia-1999-2010?type=dataset
https://data.opendevelopmentmekong.net/dataset/substations

**Comment by punwath** [comment]
Now this problem still happens again.
Before add the new resource
![image](https://cloud.githubusercontent.com/assets/18112596/17162397/efb77b26-53df-11e6-93e6-377e48561e79.png)
After add new resource the label disappears.
![image](https://cloud.githubusercontent.com/assets/18112596/17162406/fe64ecc6-53df-11e6-810e-96089dcec4dc.png)

Link: https://data.opendevelopmentmekong.net/dataset/mining-license-in-cambodia-1995-2014-type-dataset

**Comment by acorbi** [comment]
Closing, this belongs to https://github.com/OpenDevelopmentMekong/ckanext-odm_dataset/issues/338
