### ISSUE TITLE
Link on CKAN doesn't work well and always changes

### ISSUE THREAD

**Issue by punwath** [OpenDevelopmentMekong/wpckan#147]
When i update the metadata and the resource of the data, the link of dataset get change. For example previoiusly the link of transmission line data is https://data.opendevelopmentmekong.net/dataset/transmission_lines?type=dataset then it is change to another link ( https://data.opendevelopmentmekong.net/dataset/transmission-lines-in-cambodia-2009-2014?type=dataset). This problem also appear to the private dataset also and it is really difficult to find the private dataset when lost the link (https://data.opendevelopmentmekong.net/dataset/kac-kyung-an-cable-16-02-2015-pdf). Moreover, the URL of the new dataset doesn't work well. I uploaded a subdegree then the URL is like this https://data.opendevelopmentmekong.net/dataset/sub

**Comment by acorbi** [comment]
@punwath @prustar is this Issue still being reproduced? @punwath can you provide concrete steps for reproducing it?

**Comment by acorbi** [comment]
@punwath is this Issue still being reproduced? if not please close this issue. If yes, please tell me

**Comment by acorbi** [comment]
@punwath is this Issue still being reproduced? if not please close this issue. If yes, please tell me

**Comment by punwath** [comment]
Thank you @acorbi . Currently, I don't face any of this problem anymore.

**Comment by acorbi** [comment]
ok @punwath, thanks for your reply. I'm closing this issue now, please re-open if the problem appears again
