### ISSUE TITLE
Show additional data fields in order

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wpckan#152]
**Datasets:**

Source
Date Created
Temporal Range
Process
Logical consistency
Completeness
Access use and Constraints
Copyright
License
Attributes
Last updated

Please add **language** to the above after license. 
All list: 
**TITLE
TAGS
ORGANISATION (only for ODM site)**

**Library:** 
Description 
Document type
Publication date
Source (would it be possible to add a citation) 
Author (only display the author if there is something entered in these fields) 
Publication place
Language
License
Access use and Constraints

**Laws, Policies and Agreements:**
Full title
Short description
Document type
Status
Adoption date
Language
License
Access use and Constraints.

**Comment by acorbi** [comment]
@prustar, there are is no **DEscription** field for library records. you mean **Short summary (contents)** ? To avoid confusion, please specify the **Field name** and not the **Field label** for each record. See https://wiki.opendevelopmentmekong.net/public:metadata

**Comment by acorbi** [comment]
@prustar also, there is no **Source** field

**Comment by acorbi** [comment]
@prustar also, there is no **short description** on laws

**Comment by acorbi** [comment]
For the record, currently we have:

** Common fields**
title,title_translated,notes_translated,odm_access_and_use_constraints

** Datasets**
odm_source,odm_date_created,temporal_range,odm_process,odm_logical_consistency,
odm_completeness,odm_copyright,license_title,odm_language,odm_attributes,odm_date_modified

** Library records**
document_type,marc21_260c,marc21_100,marc21_260a,odm_language,license_title

**Laws records**
odm_document_type,odm_laws_status,odm_promulgation_date,odm_language,license_title,

**Comment by acorbi** [comment]
@prustar the implementation part of the issue is done. that is why i am closing it, once you provide me with the final list of **field names** it is just a matter of adding them to config.

**Comment by prustar** [comment]
@acorbi -- from the top again: 

**Datasets:**

TITLE= title
Description = notes
ORGANISATION (only for ODM site)= organisation
Source = odm_source
Date Created= odm_date_created
Temporal Range = odm_temporal range
Process = odm_process
Logical consistency = odm_logical_consistency
Completeness = odm_completeness
Access use and Constraints = odm_access_and_use_constraints
Copyright = odm_copyright
License= license_title
Language = odm_language
Attributes= odm_attributes
Last updated = odm_date_modified.

**Library:** 
Full formal title= title
Description = notes
Document type = document_type
Publication date = marc21_260c
Source (would it be possible to add a citation)***** = odm_contact
Author (only display the author if there is something entered in these fields) = marc21_100, marc21_110, marc21_700, marc21_710
Publication place = marc21_260a
Language = odm_language
copyright = odm_copyright
Access use and Constraints = odm_access_and_use_constraints

**Laws, Policies and Agreements:**
Full title = title
Short description = notes
Document type = odm_document_type
Status = odm_law_status
Adoption date = odm_promulgation_date
Language = odm_language
License = odm_license
Access use and Constraints = odm_access_and_use_constraints

It would be nice in the detailed data records page to provide a citation format for users who source information from our site. We do have a standardised text in the wiki, I've added it here: Can we auto-fill title? 

_Creating: Publishing works produced/generated from Open Development Mekong content._
This work, “[Title of your work with hyperlink here]”, is a derivative of “[**title**/generated by Open Development Mekong with hyperlink]” by Open Development Mekong, used under CC-BY-SA. “[Title of your work here]” is licensed under CC-BY-SA by [Your name here].

_Adapting: Publishing works modified, transformed and built upon Open Development Mekong content._
This work, “[Title of your work with hyperlink here]”, is an adaptation of “[**title**/generated by Open Development Mekong with hyperlink]” by Open Development Mekong, used under CC-BY-SA. [Briefly explain the modification or transformation] “[Title of your work here]” is licensed under CC-BY-SA by [Your name here].
