### ISSUE TITLE
My widget "Archive Post as CKAN dataset" doesn't work

### ISSUE THREAD

**Issue by thenets** [OpenDevelopmentMekong/wpckan#159]
==== SOLVED AND BUG IDENTIFIED ====
I go back to the version 1.2.1 and everything works fine. Probably is a bug.
If you need some information for debugging, just let me know.

Thanks for working on this plugin! :)
See ya.

==== OLD POST: ====
I don't know why, but the "Archive Post as CKAN dataset" on post editor doesn't work :/
I have set the CORS on my CKAN and the "Add related CKAN content" works fine.

Below you can see all fields empty on "Archive Post as CKAN dataset":
![Widget on Post editor](https://cloud.githubusercontent.com/assets/2138276/17086209/dba577c4-51c2-11e6-922e-6c4f077fd8cd.png)

If was necessary, this is my CKAN instance (I'm working on theme):
http://dev.thenets.org/dataset

![wpckan's Settings](https://cloud.githubusercontent.com/assets/2138276/17085211/4d9b85cc-51a9-11e6-8a49-d3798ac71315.png)

I've got this output on log file:
```
SERVER_IP - 2016-07-24 20:54:10 - 3 - [ /var/www/dadosabertos/wp-content/plugins/wpckan/utils/wpckan-api.php | 465 ] ERROR API CALL on wpckan_api_get_organization_list_for_user message: The directory "/cache/" does not exist and could not be created.
SERVER_IP - 2016-07-24 20:54:10 - 3 - [ /var/www/dadosabertos/wp-content/plugins/wpckan/utils/wpckan-utils.php | 399 ] Something went wrong, check your connection details
```
But where should be located this "/cache" dir? On Wordpress installation? On system root?

Thanks!

**Comment by acorbi** [comment]
Hi  @thenets thanks for raising this.

I understand you have enabled cache on the WPCKAN settings and specified /cache as path for the the folder storing the cached contents. You have to make sure then that the /cache folder does exist on the machine running your wordpress installation and that the folder is writable. Then WPCKAN should be able to store the cached contents returned by the queries done to the CKAN api

**Comment by thenets** [comment]
By now, the version 1.2.1 solved my problem ^^ I'll keep this version.
I hope I have helped you.
Thanks for this app! ^^

**Comment by acorbi** [comment]
@thenets with pleasure! Can you please share with me the site where you are using the plugin? Im curios to see your use-cases...

**Comment by thenets** [comment]
I'm just using on development environment. But I'm working with dados.gov.br . I'll release a new version on next month. :)

**Comment by acorbi** [comment]
Sweet! I covered dados.gov.br in some of the events we did in Brazil as part of http://open-steps.org. So you are using the archiving feature of WPCKAN? also the others?

**Comment by thenets** [comment]
I'm just implementing all features was requested to me. So I don't know what is the final purpose of all this features.
I'm focus on a good CKAN installer, like my project Easy CKAN, and a good and simple way to deploy, using Docker with Easy CKAN command line.

Just mail me if you want to chat. ^^
