### ISSUE TITLE
ODC Metadata on Frond-End: #Issues with bi-lingual field

### ISSUE THREAD

**Issue by ChandaraKhun** [OpenDevelopmentMekong/wpckan#171]
Eng/Khmer don't work properly with some fields of the metadata for the dataset.
This happens on Frond-End of ODC website. 
![screencapture-cambodia-opendevelopmentmekong-net-km-dataset-1473132134492](https://cloud.githubusercontent.com/assets/10953792/18261193/384e1926-741f-11e6-8fca-d45f9060ce2f.png)

**Comment by acorbi** [comment]
@ChandaraKhun my comments to this issue:

1. Why would you suggest to hide the organization and the tags/topics the dataset is tagged with? Can you specify a reason for it or make an improvement request?

2. the translation issues on the additional data are now fixed.

3. the presented datasets on the sidebar are the most viewed datasets in general. If you consider the title of the widgtes is not correct, please change it under **Appearance > Widgets** after consulting with @DBishton
