### ISSUE TITLE
Author/Maintainer: Removal of Fields

### ISSUE THREAD

**Issue by ChandaraKhun** [OpenDevelopmentMekong/wpckan#173]
CKAN metadata fields: Maintainer, Maintainer Email, Author & Author Email shall not be shown to the public. This field may be better served for the internal use only, the back-end of the CKAN.

**Suggestion**: Only the field "Maintainer: Open Development Cambodia (ODC)" and "Maintainer email: info@opendevcam.net" may be shared with the public/users. 
![screenshot_3](https://cloud.githubusercontent.com/assets/10953792/18335491/eddb29ec-75a9-11e6-9413-23d64a279f35.jpg)

**Comment by acorbi** [comment]
Moving to https://github.com/OpenDevelopmentMekong/ckanext-odm_dataset/issues/339 , https://github.com/OpenDevelopmentMekong/ckanext-odm_nav/issues/68 and https://github.com/OpenDevelopmentMekong/ckanext-odm_laws/issues/64. Closing this one
