### ISSUE TITLE
Related content issues on topic pages

### ISSUE THREAD

**Issue by ChandaraKhun** [OpenDevelopmentMekong/wpckan#176]
The "Related ..." (News, Laws, Library Records) does still have issues:
-This shall show the "Related..." instead of the last updated .
-The related records shall come from OD Cambodia CKAN data hub instead of OD Mekong.
![screencapture-opendevelopmentcambodia-net-topics-elections-1473648127045](https://cloud.githubusercontent.com/assets/10953792/18423369/9df8e48c-78ce-11e6-8fea-b55f2f658f2f.png)

**Comment by acorbi** [comment]
thanks @ChandaraKhun will check...

**Comment by acorbi** [comment]
@ChandaraKhun this is now fixed, closing
