### ISSUE TITLE
Some fields in library records not translating to khmer

### ISSUE THREAD

**Issue by ChandaraKhun** [OpenDevelopmentMekong/wpckan#184]
Recently, some metadata fields on CKAN (Library) in Khmer did not work properly.
This was noticed in the last 3-4 weeks. 

![screencapture-data-opendevelopmentmekong-net-km-dataset-list-of-land-for-mineral-concession-areas-draft-1475570377244](https://cloud.githubusercontent.com/assets/10953792/19068174/aa517684-8a4b-11e6-8d73-19b24678aca9.png)

**Comment by acorbi** [comment]
@ChandaraKhun those strings are still untraslated on the corresponding transifex projects for the Khmer language:
- https://www.transifex.com/open-development-mekong/odm-ckanext-odm_dataset/languages/
- https://www.transifex.com/open-development-mekong/odm-ckanext-odm_laws/languages/
- https://www.transifex.com/open-development-mekong/odm-ckanext-odm_library/languages/
- https://www.transifex.com/open-development-mekong/odm-ckanext-odm_nav/languages/

@gimmemochi can you please coordinate the completion of these pending translations?

**Comment by gimmemochi** [comment]
@ChandaraKhun there are 23, 26, 20, and 3 strings needed translation for each of the package respectively. Could you coordinate with your editors? Let me know if you can questions or concerns.

**Comment by ChandaraKhun** [comment]
@acorbi @gimmemochi thanks!

**Comment by acorbi** [comment]
@ChandaraKhun are these strings now translated on transifex? can we close this issue?

**Comment by acorbi** [comment]
@ChandaraKhun ping

**Comment by ChandaraKhun** [comment]
@acorbi If it is not an error of the bi-lingual field but editorial/translation, close this issue please.
Thanks!
