### ISSUE TITLE
Some fields in Law records not translating to khmer

### ISSUE THREAD

**Issue by ChandaraKhun** [OpenDevelopmentMekong/wpckan#185]
Khmer version in some fields of CKAN metadata (law) did not work.
This only happened in the last 3-4 weeks; previously it work.

![screencapture-data-opendevelopmentmekong-net-km-dataset-prakas-no-802-on-allowing-brewer-natural-resources-development-co-ltd-to-search-for-mines-1475570890301](https://cloud.githubusercontent.com/assets/10953792/19068255/10a43ef8-8a4c-11e6-95d5-9878f6fe58ea.png)

**Comment by acorbi** [comment]
@ChandaraKhun the data in this record is incorrectly mantained. Please see on the api call the data which is currently stored: https://data.opendevelopmentmekong.net/api/3/action/package_show?id=prakas-no-802-on-allowing-brewer-natural-resources-development-co-ltd-to-search-for-mines

There are 2 issues:

1. Short title has both Khmer and English contents. please split/separate.
![screenshot from 2016-10-24 15-10-40](https://cloud.githubusercontent.com/assets/384894/19659971/0aed4652-99fc-11e6-9128-6f5216e24721.png)

2. Access and use constraints has the same text for both languages. please split/separate.
![screenshot from 2016-10-24 15-11-28](https://cloud.githubusercontent.com/assets/384894/19660008/311a090a-99fc-11e6-9c3a-aadd745fac9a.png)

**Comment by acorbi** [comment]
@ChandaraKhun did you see my reply? was it fixed? can we close this issue?

**Comment by acorbi** [comment]
@ChandaraKhun ping

**Comment by ChandaraKhun** [comment]
@acorbi if that is not an error resulting from CKAN but editorial, yes close this issue please. 
Thanks!
