### ISSUE TITLE
Overcome limit of 1000 records for wpckan get_datastore calls

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wpckan#191]
Currently, the **wpckan_get_datastore** returns a maximum of 1000 records due to the internal limitations of CKAN. A solution should be found in order to be able to obtain more than 1000 records through this function. This is critical for the proper functioning of the laws pages.

**Comment by Huyeng** [comment]
@acorbi, could you please add this task into your priority list.

**Comment by acorbi** [comment]
@Huyeng it is already on it. I estimate I can fix it by monday

**Comment by Huyeng** [comment]
Great!

**Comment by acorbi** [comment]
@Huyeng Fixed and deployed on PP. Please review
