### ISSUE TITLE
The widget of wpckan Query Resource doesn't show Khmer

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wpckan#192]
Most the dataset, laws and library records of this page available in Khmer, but on khmer site still list as English. 
![screenshot_3](https://cloud.githubusercontent.com/assets/6613530/20559334/82618c54-b1a6-11e6-80f0-9a95c9e34cfb.jpg)

![screenshot_4](https://cloud.githubusercontent.com/assets/6613530/20559374/b5a2cf1a-b1a6-11e6-9fd9-6652b7906272.jpg)

**Comment by acorbi** [comment]
Issue can be reproduced on https://opendevelopmentcambodia.net/km/profiles/forest-cover

**Comment by Huyeng** [comment]
It is not only the forest cover page, but also all the topic pages as well: 
eg. https://opendevelopmentcambodia.net/km/topics/agriculture-and-fishing/

**Comment by acorbi** [comment]
@Huyeng thanks. please do not forget to add links to the URLs where the issues can be reproduced as indicated on https://wiki.opendevelopmentmekong.net/public:bug_reporting

**Comment by acorbi** [comment]
@Huyeng This Issue relied on the configuration of the widgets. In order to show the translated title, you need to add **title_translated** to the list of fields to output, and not only **title**: See

![screenshot from 2016-11-23 14-47-06](https://cloud.githubusercontent.com/assets/384894/20564146/1dd11602-b18c-11e6-9624-82b3aead3dab.png)

**Comment by Huyeng** [comment]
It looks fine on the widget now. 
Anyways, I would like to suggest to set the translated field as default in code, otherwise, we need to add the translated attribute to all the using widget for the country sites (ODC, ODV, and ODMm). 
The attributes that need to add in the output fields for dataset should be the field that basic attributes, and translated field will be automatically added/used on the localization page.

**Comment by acorbi** [comment]
@Huyeng good sugestion. I have created a separate issue on https://github.com/OpenDevelopmentMekong/wpckan/issues/194 . closing this
