### ISSUE TITLE
Some texts on detail page are not translated 

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wpckan#204]
https://opendevelopmentcambodia.net/km/dataset/?id=http-web-archive-org-web-20150708083757-http-www-cdri-org-kh-webdata-download-wp-wp63e-pdf

![screenshot_6](https://cloud.githubusercontent.com/assets/6613530/21180312/f50fcf4c-c22a-11e6-826d-078b665071a8.jpg)

**Comment by acorbi** [comment]
@Huyeng can this Issue still be reproduced?

**Comment by acorbi** [comment]
@Huyeng I have been checking this and the problem relies on the fact that there are many strings still to translate on https://www.transifex.com/open-development-mekong/odm-wpckan/wpckan-enpo/

**Comment by acorbi** [comment]
@Huyeng @ChandaraKhun can you please tell me when the strings have been translated on https://www.transifex.com/open-development-mekong/odm-wpckan/wpckan-enpo/ so I deploy them?

**Comment by Huyeng** [comment]
@acorbi the strings that appear on the detail page are already translated. Those strings that have not translated are using in back-end. See below:
https://www.transifex.com/open-development-mekong/odm-wpckan/viewstrings/#km/wpckan-enpo/105059469?q=Document%20type

https://www.transifex.com/open-development-mekong/odm-wpckan/viewstrings/#km/wpckan-enpo/105059350?q=Copyright

https://www.transifex.com/open-development-mekong/odm-wpckan/viewstrings/#km/wpckan-enpo/105059300?q=Co-author%20(individual)

**Comment by acorbi** [comment]
hey @huyeng, thanks for replying. i'll deploy the translations then. please ping me everytime new translations are added and need to be deployed. A quick chat message is enough

**Comment by Huyeng** [comment]
Those are not new translated. But I don't know why they are shown on Khmer site, before they did.

**Comment by prustar** [comment]
@Huyeng -- might be the data entry staff error here.
