### ISSUE TITLE
CSV in Khmer language doesn't show

### ISSUE THREAD

**Issue by punwath** [OpenDevelopmentMekong/wpckan#212]
I added a CSV in Khmer language and uploaded to the data store already in CKAN but it could not load view: DataProxy returned an error (Request Error: Backend did not respond after 10 seconds).  Here is the link to the CSV:https://data.opendevelopmentmekong.net/en/dataset/registered-communal-land/resource/372129f9-e274-44f3-96c2-bd0395105e7c#

**Comment by acorbi** [comment]
@punwath  when I open that link I can see the table view without problems. Maybe a connection issue from your side? The error message sounds like timeout.

![screenshot from 2016-12-16 09-02-04](https://cloud.githubusercontent.com/assets/384894/21255791/555375fe-c36e-11e6-8f5f-c0d921cc28cb.png)

# IMPORTANT

Currently, we are preparing the deployment of the new code on CKAN and therefore NO DATA should be uploaded to the CKAN PRODUCTION instance. If you need to upload or change some data please contact me or @prustar on gitter / email.

**Comment by punwath** [comment]
But why the Khmer words doesn't show up?

**Comment by acorbi** [comment]
Oh I see, there are values in khmer on those blank columns. I could download the file and see the contents so it is a display issue. Let me check it and I'll update you over here.

So, do you need to do some changes on CKAN? Can you tell me which ones? Please mind the warning on my last comment.

**Comment by punwath** [comment]
Now I need that CSV uploaded in the dataset because it is for profile page. Thank

**Comment by acorbi** [comment]
Is it a new profile page? If so, when are you planning to complete it? 

or is it an existing one? If so, which one is it?

**Comment by punwath** [comment]
it is the existing one of indigenous communities

**Comment by acorbi** [comment]
yeah, there is a problem with the file in Khmer. I'm looking at it now

**Comment by acorbi** [comment]
@punwath I found the error:

```
sqlalchemy.exc.ProgrammingError: (ProgrammingError) column "reference" specified more than once
```
![screenshot from 2016-12-16 10-13-10](https://cloud.githubusercontent.com/assets/384894/21257423/68d14c96-c378-11e6-9abc-3e0010bac812.png)

The column reference is duplicated, please fix and re-upload

**Comment by acorbi** [comment]
@punwath I see you have fixed the issue. please inform me next time over here so I can close the issue.
