### ISSUE TITLE
Datasets with same title are merged by CKAN

### ISSUE THREAD

**Issue by punwath** [OpenDevelopmentMekong/wpckan#234]
I already published a library record and then I also published a data which has the name like library record. After that the library record got merged into the data and the metadata of library record was replaced by the data metadata.
-Library Record: https://data.opendevelopmentmekong.net/library_record/contact-list-for-edc-customers-test
-Data : https://data.opendevelopmentmekong.net/dataset/contact-list-for-edc-customers-test

![image](https://cloud.githubusercontent.com/assets/18112596/22458441/22fc3caa-e7cf-11e6-8bd6-c6517cd275e2.png)
![image](https://cloud.githubusercontent.com/assets/18112596/22458453/2d9529b0-e7cf-11e6-9211-fc5fc6121ac9.png)

That PDF file is the resource from Library record.

**Comment by acorbi** [comment]
@punwath thanks for raising this. I am moving the issue to https://github.com/OpenDevelopmentMekong/ckanext-odm_dataset/issues/390 and will take care of it asap.
