### ISSUE TITLE
Add Related Dataset Metabox is not working 

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wpckan#236]
On topic page, when the keywords are typed, there is a list of suggested dataset is not appeared and add button can't click. 
![screenshot_1](https://cloud.githubusercontent.com/assets/6613530/22818321/40542d44-ef9f-11e6-9777-f5656372b189.jpg)

**Comment by acorbi** [comment]
![screenshot from 2017-02-13 15-36-05](https://cloud.githubusercontent.com/assets/384894/22887556/d692a262-f202-11e6-9379-d141867e0410.png)
