### ISSUE TITLE
 An internal server error occurred for a dataset

### ISSUE THREAD

**Issue by punwath** [OpenDevelopmentMekong/wpckan#244]
When switch from English page to Khmer page, the Electricity price and coverage areas in Cambodia dataset, error 505 appears. But on the English side is working fine.

URL: https://data.opendevelopmentmekong.net/km/dataset/electricity-price-and-coverage-areas-in-cambodia?type=dataset

**Comment by acorbi** [comment]
@punwath this issues has been now fixed via https://github.com/OpenDevelopmentMekong/ckanext-odm_agreement/issues/6

please test on PROD and provide feedback
