### ISSUE TITLE
Change the date format in Additional info table

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wpckan#251]
The date format in this page is not consistent.  Suggest to change the format to dd mmm yyyy. eg 02 Mar 2017. 

![screenshot_1](https://cloud.githubusercontent.com/assets/6613530/23493322/834e4aa0-ff3d-11e6-93a5-c226fb63a33c.jpg)

Suggest to implement this for the profile page, law page and library record as well.

**Comment by Huyeng** [comment]
It looks good. However, I would like to suggest to use the format 02 Mar 2017 instead. Using digit 03/02/2017 like this is quit confuse as in Cambodia and other country day is read first. 

the standard of date in wiki, https://wiki.opendevelopmentmekong.net/partners:editorial_guidelines#style, is DD Month YYYY.

**Comment by acorbi** [comment]
good point @Huyeng , I'll change it.
