### ISSUE TITLE
Keywords 

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wpckan#262]
@acorbi - don't know where to file this. 

You can't add keyword strings to the new field in CKAN for instance I wanted to include a keyword tag for a company name specifically 'Vesan Investments'. The field would only accept a single word for this name which is less than idea. 

We want to us the taxonomy as a structure to standardise terms for categorising them for monitoring but allow the keywords to be unstructured to be able to more intuitively fine tune the results from searches etc.  As there are no keywords as yet in the system when it was looking for them nothing came up. Is the field programmed to display related or similar terms when you type so as to avoid duplicates?

**Comment by acorbi** [comment]
moving to https://github.com/OpenDevelopmentMekong/ckanext-odm_dataset/issues/419. @prustar see my comments there
