### ISSUE TITLE
Agreement metadata: Editorial issues on WordPress

### ISSUE THREAD

**Issue by ChandaraKhun** [OpenDevelopmentMekong/wpckan#266]
The labeling of few fields on CKAN Agreement metadata does not show properly on ODC WordPress front-end, leading to the editorial issues. https://opendevelopmentcambodia.net/dataset/?id=3e6f05ab-1e84-4df7-a092-af922280ee31 
![screencapture-opendevelopmentcambodia-net-dataset-1491987463690](https://cloud.githubusercontent.com/assets/10953792/24952270/28d455d6-1fa1-11e7-9bb8-3f1e301ffa9b.png)

**Comment by acorbi** [comment]
@ChandaraKhun this is now fixed. It involved no code change but configuration of the WPCKAN settings as indicated on https://wiki.opendevelopmentmekong.net/partners:configuring_frontend_2_0#creating_and_configuring_a_dataset_detail_page

Concretely, this field:

![screenshot from 2017-05-16 10-15-10](https://cloud.githubusercontent.com/assets/384894/26096254/cf8e511c-3a20-11e7-8230-571afb0896b1.png)

Closing now
