### ISSUE TITLE
Archive all the old contents of ODC into CKAN systematically 

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wpckan#27]
wp_ckan will archive the new posts only into CKAN if the setting is selected. How the plugin will be implemented related to the old contents of ODC that will be migrated? It would be great, if the wp_ckan plugin can archive those contents automatically into CKAN.

**Comment by acorbi** [comment]
Good point @Huyeng!. Possible approaches are:
- Develop extra script for importing old contents.
- Modify wpckan to include a "bulk" archiving function

**Comment by acorbi** [comment]
Implemented with script in https://github.com/OpenDevelopmentMekong/ckanext-odm_utils
