### ISSUE TITLE
wpckan crashes if you put a directory as log

### ISSUE THREAD

**Issue by terchris** [OpenDevelopmentMekong/wpckan#276]
Installing wpckan for the first time I put a path to a directory in the field named "Log file path". The reason for putting a directory and not a file here is that the text below the field reads "Path where logs are going to be stored. Mind permissions."
I assumed that it had to be a directory because "logs" means more than one.

This caused wp-admin to crash and I was not able to admin my site. I had to read up a lot about how to fix the problem of misbehaving plugins. Add logging to wordpress and find the problem.

The simple fix to this is to remove the "s" in "logs" text. A better fix is to do a test before trying to open the file in your code.

**Comment by acorbi** [comment]
hi @terchris, many thanks for raising this issue, which I just fixed. Now, wpckan is going to check that the path specified points to a file, if not a warning message will be shown on the dashboard.

May I ask what you are using wpckan for? I would be very interested on knowing about how you and/or your organization is making use of it
