### ISSUE TITLE
Call to undefined function odm_country_manager() in .... wpckan/templates/dataset-detail.php:39

### ISSUE THREAD

**Issue by terchris** [OpenDevelopmentMekong/wpckan#279]
Call to undefined function odm_country_manager() in .... wpckan/templates/dataset-detail.php:39

Got this error when testing this:

Feature 4: Show dataset detail
The plugin exposes a shortcode which can be used to output the metadata and resources of a CKAN dataset, specified by id parameter

id: String. Unique identifier of the dataset
Examples:

[wpckan_dataset_detail id="ckan-dataset-one"]

**Comment by acorbi** [comment]
@terchris thanks for raising this.

Some non-generic code slipped into the code base. I have added some **function_exists** calls to avoid this issue.

Can you pull the latest code and try again?
