### ISSUE TITLE
[Wordpress] Download: Inconsistent font size 

### ISSUE THREAD

**Issue by ChandaraKhun** [OpenDevelopmentMekong/wpckan#294]
Font size for "Download English/Khmer PDF", on Announcement, appears inconsistent in both English and Khmer. 
Link: https://opendevelopmentcambodia.net/announcements/the-temporary-number-of-cambodians-voter-turnout-in-the-commune-election-in-the-fourth-legislature-4-june-2017/#!/story=post-105209
![i227 cimgpsh_orig](https://cloud.githubusercontent.com/assets/10953792/26822648/fd0773ac-4ad4-11e7-835c-4c45ee45a881.jpg)

**Comment by acorbi** [comment]
moving to https://github.com/OpenDevelopmentMekong/wp-odm_theme/issues/989 where it belongs.

@ChandaraKhun The issue you raised is related to the main theme (wp-odm_theme) not the wpckan plugin.

Closing
