### ISSUE TITLE
Problem connecting to CKAN instance. Please, check the specified URL.

### ISSUE THREAD

**Issue by Rjones8901** [OpenDevelopmentMekong/wpckan#296]
Getting this issue when trying to connect a CKAN site to WP. URL is correct, thoughts?

**Comment by Rjones8901** [comment]
Resolved by installing the PHP cURL extensions which are required by Guzzle

**Comment by acorbi** [comment]
Thanks @Rjones8901, will add the dependency to the README.md

**Comment by acorbi** [comment]
Well, it is actually already there :sweat_smile:
