### ISSUE TITLE
Layout improvements on dataset detail page

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wpckan#297]
![screenshot from 2017-06-07 09-16-31](https://user-images.githubusercontent.com/384894/26867260-ea3f1d52-4b64-11e7-9f8f-0ca685677789.png)

https://opendevelopmentmekong.net/dataset/?id=038386c8-2cbd-405a-a15a-1345c38095f9

- limit the length of long descriptions and provide option to expand
- limit the length of long descriptions on **resources** and provide option to expand
- invert position of resources and additional sections (resources down)
- modify additional info section to be configured with 2 sections ( important metadata and additional info, which will be collapsed)
- layout the additional info section differently (instead of table layout present the metadata values underneath the labels)
- show thumbnail if resources are images. (https://github.com/OpenDevelopmentMekong/wpckan/issues/217)

## Some considerations

* Need to reduce duplicates in the metadata - don't repeat the title, tags and description within the metadata fields.
* For different resource types there should be a different list of metadata priorities to be displayed - Alex can you find the original that we specified initially? This may have changed and we need to priorities for agreements still. 
* I prefer the paragraph view but understand that the table view reduces scroll, formatting of the table is better. 

## Questions

- How can we layout the page  if there are no related datasets/library publications/laws?

## Sub tasks

- [x] @DragonVirus will prepare mockup, 
- [x] Alex will coordinate implementation

**Comment by acorbi** [comment]
Design proposed by @DragonVirus on https://drive.google.com/drive/folders/0BymS3LWpLYfoZmFpS3NSX2FFT28

**Comment by acorbi** [comment]
@Huyeng @ChandaraKhun @prustar @gimmemochi @DBishton please see design proposed by @DragonVirus and add comments/questions/suggestions

**Comment by gimmemochi** [comment]
@acorbi I've reviewed the mockups and added some comments to the Google Doc.

**Comment by acorbi** [comment]
This issue has now being splitted into smaller, modularized tasks across repositories which are listed on https://docs.google.com/document/d/1pmT-rrj0uOOIqlHpSiA-1CGTGzXFC7xrwmTNrF6h-D8/edit#. Closing this.
