### ISSUE TITLE
CKAN Dataset Metadata: Reporting the required fields in "red"

### ISSUE THREAD

**Issue by ChandaraKhun** [OpenDevelopmentMekong/wpckan#298]
This dataset metadata still shown the required fields to be fill in, although it was already completed.
As marked in Red, the word "Agreement" appeared in the place of "Dataset"
![screenshot_4](https://user-images.githubusercontent.com/10953792/26918524-9d991824-4c5c-11e7-8c4a-a779436fdcdd.jpg)

Link: https://data.opendevelopmentmekong.net/en/dataset/results-on-the-national-assemblys-election-2003

**Comment by acorbi** [comment]
Thanks @ChandaraKhun 

That record is not an agreement, so the message should not appear. I believe this is a bug that I will investigate. please ignore for the moment.

**Comment by acorbi** [comment]
moving to https://github.com/OpenDevelopmentMekong/ckanext-odm_dataset/issues/439
