### ISSUE TITLE
List other search results on the widgets of dataset detail page if the solr_search parameter is set

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wpckan#303]
Related to https://github.com/OpenDevelopmentMekong/wpckan/issues/295. Implementation of bullet (2)
on diagramm below:

As per mockup by @prustar 

![screenshot from 2017-04-04 23-35-07](https://cloud.githubusercontent.com/assets/384894/24679958/5b5e1c8e-198f-11e7-8fb6-c7f2d5971a7b.png)

**Comment by gimmemochi** [comment]
I really like the request for adding "Related to this dataset" which I believe is Pyrou's (2). 

Questions: How are the "Most viewed laws" and "Most viewed datasets" selected? Are they records from the same topics/categories? OR are they most viewed laws and dataset across CKAN in general (independent of the topic of the dataset being previewed on this page)?

**Comment by acorbi** [comment]
@gimmemochi sorry, I oversaw your comment.

> Questions: How are the "Most viewed laws" and "Most viewed datasets" selected?Are they records from the same topics/categories? OR are they most viewed laws and dataset across CKAN in general (independent of the topic of the dataset being previewed on this page)?

It depends on which widgets are currently configured. Country site editors/admins have the chance to configure that sidebar and add a series of widgets to display related info. Currently, all sites are featuring 3 instances of **WPCKAN Query resources by post's category** on the **WPCKAN Dataset detail sidebar**, each of them showing datasets, laws_records and library_records respectively.

**Comment by acorbi** [comment]
Moving to https://github.com/OpenDevelopmentMekong/wp-odm_theme/issues/1054 where it belongs. closing this issue
