### ISSUE TITLE
Warning: strpos() expects parameter 1 to be string

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wpckan#306]
Warning: strpos() expects parameter 1 to be string, array given in \plugins\wpckan\utils\wpckan-utils.php on line 617

![screenshot_9](https://user-images.githubusercontent.com/6613530/27126993-80ee2bda-5123-11e7-893c-4dc07393abe4.jpg)

**Comment by acorbi** [comment]
@Huyeng thanks for raising this, I will fix it now.
