### ISSUE TITLE
Couple of issues with current build 2.2.7 on install

### ISSUE THREAD

**Issue by Rjones8901** [OpenDevelopmentMekong/wpckan#310]
Issue with Warning: require(/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/wp-content/plugins/wpckan-master/wpckan.php on line 11
even when I am seeing the vendor directory and autoload.php file after using composer install.

Issue with the composer install with guzzle
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.

Issue with Class 'Gilbitron\Util\SimpleCache' not found in /var/www/html/wp-content/plugins/wpckan-master/wpckan.php on line 25 after commenting out line 11.

**Comment by acorbi** [comment]
@Rjones8901 can you provide some Info about your development environment? Are you using Xampp by any chance? Seems that there is some Issues with the autoload mechanisms: https://stackoverflow.com/questions/18312707/why-my-autoload-php-of-composer-doesnt-work

@Huyeng this might be related to https://github.com/OpenDevelopmentMekong/wp-odm_solr/issues/80

**Comment by Rjones8901** [comment]
AWS EC2 Ubuntu 14 instance

**Comment by Rjones8901** [comment]
I was able to resolve this. The installation method was not correct. The person who was trying to install the plugin was downloading the zip and using WP GUI to try and install the plugin. This failed, but removing the plugin and then installing via CLI in putty with composer worked.
