### ISSUE TITLE
Integrate GA library for tracking download events

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wpckan#314]
The new **google analytics javascript library** could be integrated into the wpckan plugin (or even better into the wp-odm_theme theme in order to be accessible by all the plugins) and used for tracking dataset download events. Concretelly, following events should be tracked:

- When the dataset detail page is loaded, an event **dataset_view** would be sent to GAnalytics containing the id of the dataset in question.

- When the user clicks on the download button for a dataset's resource, an event **resource_download** would be sent to GAnalytics  containing the id of the dataset and the id of the resource.

- OPTIONAL: When the user user clicks on a related dataset listed on the sidebar, an event **related_dataset_link** would be sent to GAnalytics containing the id of the dataset the user is being linked to.

- [ ] Integrate GA javascript library (optimally via composer)
- [ ] Create additional js file under /js/ which contains javascript code

**Comment by DragonVirus** [comment]
> When the dataset detail page is loaded, an event dataset_view would be sent to GAnalytics containing the id of the dataset in question.

@acorbi i think this is currently logged as page view. Right ? Can you explain a bit why this one needed as event ?

**Comment by acorbi** [comment]
@DragonVirus It should be registered as page view yes. however I would suggest to track this as event as well in order to have more structured/cohesive data to analyze user's behaviour. It might be more convenient to have those events in order to compare with the download events, that way we can know the amount of users which drop-off the dataset detail pages without downloading a resource.
