### ISSUE TITLE
CKAN convert dash (-) to date

### ISSUE THREAD

**Issue by punwath** [OpenDevelopmentMekong/wpckan#330]
I uploaded a csv file that has dash (-) in the column and then CKAN converted the dash to the date.  

On spreadsheet
![image](https://user-images.githubusercontent.com/18112596/29305304-3dae253a-81c2-11e7-96ba-9495565b1ecb.png)

On CKAN: https://data.opendevelopmentmekong.net/dataset/-identification-services/resource/b94510cc-24e2-44a8-bd61-3284df0f62a8?type=dataset
![image](https://user-images.githubusercontent.com/18112596/29305316-4b87f5dc-81c2-11e7-82f2-62fca1a65fba.png)

**Comment by prustar** [comment]
@punwath -- you can't upload '-' in a CSV as CKAN won't recognise this. If there is no number can you not leave it blank? If you must use some thing perhaps try ' prior to the - or use n/a.
