### ISSUE TITLE
Data Sharing: Filter option on data detail page for different organisations

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wpckan#335]
Now that we have expanded the datasharing facility and have a number of organisations on board, we actually have a reporting requirement for MRLG that needs to specify how many of their partners have contributed to our platform and they need to report how many records they have contributed. To reduce the burden on us creating these reports, and providing to partners it would be great if we could have a filter option on the data page to filter by organisation. 

[filter.pdf](https://github.com/OpenDevelopmentMekong/wpckan/files/1371122/filter.pdf)

**Comment by acorbi** [comment]
Moving to https://github.com/OpenDevelopmentMekong/wp-odm_solr/issues/210 and closing this
