### ISSUE TITLE
Error CSV on CKAN : Process completed but unable to post to result_url

### ISSUE THREAD

**Issue by punwath** [OpenDevelopmentMekong/wpckan#336]
I am trying to upload the CSV to CKAN and the meet an issue about "unable to post to result_url" as below:
![image](https://user-images.githubusercontent.com/18112596/31803453-fe97968e-b57d-11e7-850a-df648183f822.png)
As this issue, I am not able view the CSV on CKAN and it affects to the profile page.
You can check this dataset: https://data.opendevelopmentmekong.net/en/dataset/allocated-land-for-social-land-concession/resource/751fbdf1-e716-4945-a7eb-eede1f79c653?type=dataset

**Comment by acorbi** [comment]
@punwath @Huyeng I have just reported this Issue to Proteus. Will inform you once they come  back to me

**Comment by acorbi** [comment]
Also, FYI: I tried uploading the same file to data.pp.opendevelopmentmekong.net (PP instance) and worked fine.

**Comment by acorbi** [comment]
@punwath @huyeng Error is fixed. File can be uploaded to datastore now
