### ISSUE TITLE
Detail page: Hide the View additional metadata if the supported fields additional is empty

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wpckan#340]
Suggest to hide the View additional metadata button if no information instead of showing No metadata available for current dataset. 
![screenshot_3](https://user-images.githubusercontent.com/6613530/32830350-73ff066a-ca27-11e7-989a-ed76894f6f0a.jpg)

**Comment by acorbi** [comment]
This is done already
