### ISSUE TITLE
An internal server error occurred on library record.

### ISSUE THREAD

**Issue by punwath** [OpenDevelopmentMekong/wpckan#348]
All the published document in library records get this errors. This happens when I click to see the metadata of a library record. For example, On CKAN when I click on a dataset like in the picture below
![image](https://user-images.githubusercontent.com/18112596/34761480-9c785130-f616-11e7-9679-375a502bc10b.png)
it will take me to the error page. URL: https://data.opendevelopmentmekong.net/en/library_record/factors-affecting-forest-area-changes-in-cambodia-an-econometric-approach

![image](https://user-images.githubusercontent.com/18112596/34761504-b475efc2-f616-11e7-97de-0141f2394a01.png)

This also happens to other library records as well.

**Comment by acorbi** [comment]
thanks @punwath will check this today

**Comment by acorbi** [comment]
Fixed by deploying latest code on prod (there was an incomplete deployment)
