### ISSUE TITLE
[internal server error occurred] For updating resource for CKAN dataset

### ISSUE THREAD

**Issue by punwath** [OpenDevelopmentMekong/wpckan#353]
I am not able to update the resource of the dataset on CKAN. I am trying to update the CSV file of https://data.opendevelopmentmekong.net/dataset/mining-license-in-cambodia-1995-2014-type-dataset
![image](https://user-images.githubusercontent.com/18112596/38660954-60856be6-3e59-11e8-8c0c-95fc2251db96.png)
After I click to update the resource, it takes me to meet the problem as below.
![image](https://user-images.githubusercontent.com/18112596/38661025-95110780-3e59-11e8-8004-af6a743f7632.png)

https://data.opendevelopmentmekong.net/dataset/mining-license-in-cambodia-1995-2014-type-dataset/resource_edit/089989d6-495a-4391-bbcd-893c6cf1b4b1

**Comment by derwas** [comment]
This issue was fixed. Closing this issue now.
