### ISSUE TITLE
[Internal server error occurred] when add law on CKAN

### ISSUE THREAD

**Issue by vatana92** [OpenDevelopmentMekong/wpckan#354]
When you go to CKAN law, and click on "Add Law", there will show a notification of "Sever Error". But it's fine for CKAN "Library"and "Agreement". 
![image](https://user-images.githubusercontent.com/19201022/39166378-820edd5c-47b3-11e8-9c78-a022de6d8f3c.png)
Then,
![image](https://user-images.githubusercontent.com/19201022/39166395-91f9416c-47b3-11e8-986b-224a12233898.png)

**Comment by derwas** [comment]
This issue was fixed. I am closing this now.
