### ISSUE TITLE
[Error] Resource title are changed. 

### ISSUE THREAD

**Issue by punwath** [OpenDevelopmentMekong/wpckan#355]
After the migration, I notice that the resource title of the dataset is changed to Laws issuing agencies. 
Example: URL: https://data.opendevelopmentmekong.net/dataset/railway-lines-of-laos?type=dataset
![image](https://user-images.githubusercontent.com/18112596/39285083-b26f1af0-4940-11e8-82ad-f33c12690545.png)

Before, it showed like this dataset. URL: https://data.opendevelopmentmekong.net/dataset/registered-indigenous-communal-land?type=dataset
![image](https://user-images.githubusercontent.com/18112596/39285108-d4be4586-4940-11e8-888a-3c6e04b51ca7.png)

**Comment by Huyeng** [comment]
Moved to https://github.com/OpenDevelopmentMekong/IssuesManagement/issues/17
