### ISSUE TITLE
Unable to upload 2 datasets with the same content but in 2 different languanges

### ISSUE THREAD

**Issue by mailannguyen** [OpenDevelopmentMekong/wpckan#356]
It should be able to access and download 1 datasets in 2 different languages - actually this is 2 datasets with the same content and same metadata but different languages. This means editor should be able to upload 2 separate files for 2 languages of 1 dataset

Ex: in the case pictured below, the Land Law in English has a hyperlink resource  while Vietnamese version has a doc. format file. Editor(s) should be able to upload both 2 forms of resources for 1 dataset on Land Law, which is now unable.

![image](https://user-images.githubusercontent.com/32632690/39682360-a61774ae-51d9-11e8-873f-584cee0cf81c.png)

![image](https://user-images.githubusercontent.com/32632690/39682377-b7fe0142-51d9-11e8-8af1-5da92f4899f6.png)

**Comment by prustar** [comment]
@mailannguyen -- you can do this. Closing issue please call me and I will show you how to do it.
