### ISSUE TITLE
CKAN: Geographic area for a dataset should be expanded to regional or world scale  

### ISSUE THREAD

**Issue by mailannguyen** [OpenDevelopmentMekong/wpckan#357]
For datasets that are applicable for the world or regions such as Asia or ASEAN, Mekong etc, it is not enough to select areas provided in the recent list of Geographic area since the list only has some Mekong and Asian countries. 

![image](https://user-images.githubusercontent.com/32632690/39683925-a20b7730-51e2-11e8-8ae5-d63d3134f880.png)

**Comment by prustar** [comment]
@mailannguyen -- I've mentioned the reasons for this limitation previously.
