### ISSUE TITLE
CKAN: An admin account cannot publish dataset

### ISSUE THREAD

**Issue by mailannguyen** [OpenDevelopmentMekong/wpckan#358]
@derwas, please check my CKAN account [mailan] why I cannot publish a dataset although  have admin role. In my account the function for publishing dataset does not appear like in @prustar 's account.

![image](https://user-images.githubusercontent.com/32632690/40098061-bbc21a9e-5903-11e8-98fa-2669320cc54c.png).

**Comment by prustar** [comment]
@mailannguyen -- please transfer this issue to the [IssuesManagement](https://github.com/OpenDevelopmentMekong/IssuesManagement/issues) repository. All issues need to be raised here ONLY. Do not raise issues elsewhere as they will not be answered.
