### ISSUE TITLE
How to bring back deleted dataset in CKAN, ODT

### ISSUE THREAD

**Issue by saowalakj** [OpenDevelopmentMekong/wpckan#362]
Can I bring back the dataset that has been deleted? Or should I enter as a new dataset?
This one: https://data.opendevelopmentmekong.net/library_record/sufficiency-economy-philosophy-thailand-s-path-towards-sustainable-development-goals. 

I tried to re-open it but its title still has the word [Deleted].
![screen shot 2561-08-15 at 13 51 09](https://user-images.githubusercontent.com/38714949/44140311-e1a44042-a0a3-11e8-83f7-ffa419593ee7.png)

**Comment by saowalakj** [comment]
@declan-derilinx can you help?

**Comment by declan-derilinx** [comment]
i've changed it to active

**Comment by saowalakj** [comment]
Thanks!
