### ISSUE TITLE
Plugin crashes javascript on post edit page

### ISSUE THREAD

**Issue by miguelpeixe** [OpenDevelopmentMekong/wpckan#39]
My dev tools is showing `Unexpected token u`. With a little research I got that this usually happens when using `JSON.parse` on `undefined` value.

**Comment by miguelpeixe** [comment]
http://stackoverflow.com/questions/13022178/uncaught-syntaxerror-unexpected-token-u-json

**Comment by acorbi** [comment]
@miguelpeixe Cannot reproduce. Can you please indicate steps for reproducing? Thanks

**Comment by miguelpeixe** [comment]
The bug is here: https://github.com/OpenDevelopmentMekong/wpckan/blob/10b8e47ac2d0a8cc1ddc103fa6d140cb509f1e09/js/wpckan_metabox_logic.js#L122-L123

`datasets_json` is `undefined` (probably when plugin is not yet configured)

**Comment by acorbi** [comment]
Exactly. Error can be reproduced when plugin cannot connect to CKAN instance. Will open a PR with a fix.
