### ISSUE TITLE
PHP fatal error

### ISSUE THREAD

**Issue by miguelpeixe** [OpenDevelopmentMekong/wpckan#40]
```
Parse error: syntax error, unexpected '[', expecting ',' or ';' in wpckan/templates/related_datasets_metabox.php on line 7
```

**Comment by acorbi** [comment]
@miguelpeixe  Cannot reproduce. Can you please indicate steps for reproducing (include connection details to CKAN instance)? Thanks
- Does this break the functionality of the plugin?

**Comment by miguelpeixe** [comment]
I believe `wpckan_get_ckan_settings()["baseUrl"];` is not allowed on my PHP version (5.3). I'll try to upgrade it.

**Comment by acorbi** [comment]
Ok, that makes sense. I am using PHP 5.5.9 on the dev environment. Thanks for trying to fix it!

**Comment by miguelpeixe** [comment]
Upgraded to 5.4 and it looks fixed!
