### ISSUE TITLE
Hook to customize meta box post types

### ISSUE THREAD

**Issue by miguelpeixe** [OpenDevelopmentMekong/wpckan#44]
We need a filter hook to enable the child theme to change the post types that the metaboxes will show up.

Basically just change this: https://github.com/OpenDevelopmentMekong/wpckan/blob/10b8e47ac2d0a8cc1ddc103fa6d140cb509f1e09/wpckan.php#L74

To this:
```php
$post_types = apply_filters('wpckan_post_types', array( 'post', 'page' ));
```

So I can perform this on the child theme:
```php
function opendev_wpckan_post_types() {
  return array('post','briefing','layer');
}
add_filter('wpckan_post_types', 'opendev_wpckan_post_types');
```

**Comment by acorbi** [comment]
Fixed in 6b58595144d019ce8996c120eba7352248ed0831
