### ISSUE TITLE
Amount of pages

### ISSUE THREAD

**Issue by miguelpeixe** [OpenDevelopmentMekong/wpckan#56]
Is there a way to find the number of pages so I can choose when to display the "next page" link?

**Comment by acorbi** [comment]
Not by the moment. However, we could think about adding "previous_page_link" and "next_page_link" parameters to the shortcode so it outputs the links to previous and next pages (if available).

Or you implement that check with the internal functions you showed me.

NOTE: We should integrate this function when we implement #50

**Comment by miguelpeixe** [comment]
That would be nice. I need to know when to give the navigation links so we don't 404 when click "next page" on the last page.
