### ISSUE TITLE
Paging is not working

### ISSUE THREAD

**Issue by miguelpeixe** [OpenDevelopmentMekong/wpckan#57]
I tried to apply paging on the shortcode and it doesn't change the page.
This is what I'm trying:
```
[wpckan_query_datasets limit="10" query="a" page="2"]
````

**Comment by acorbi** [comment]
Have you checked that there are enough related datasets so pagination can take place? Consider that if you set limit to 10 (10 datasets per page) and specify page = 2, then there have to be more than 10 datasets.

**Comment by miguelpeixe** [comment]
I've just tried different variations (`limit="2" page="2"`) with no luck

**Comment by acorbi** [comment]
Ok, i know the reason. wpckan depends on https://github.com/OpenDevelopmentMekong/CKAN_PHP which was updated for this version, so you need to pull the latest code. For that:

<code>
cd wp-content/plugins/wpckan/vendor/silex/ckan_client/
git pull origin master
</code>

Then i should be working.

**Comment by miguelpeixe** [comment]
Worked! Thanks
