### ISSUE TITLE
Add onlyWithDataset parameter

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wpckan#62]
wpckan_related_datasets, wpckan_number_of_related_datasets and wpckan_query_datasets should get an extra parameter that tells the plugin just to return those datasets with 1 or more resources in it.

**Comment by WillieShubert** [comment]
Hi @acorbi  I know this ticket is closed but I'm not quite seeing the functionality as yet. I'm attaching a search for water in the results pages. There is an area for data results and it is populating stories. 

![data_results_odm](https://cloud.githubusercontent.com/assets/3870349/6315719/40bf6eb8-b9d9-11e4-992c-90ee68728b2a.png)

**Comment by acorbi** [comment]
@WillieShubert This functionality can be activated by adding the filter="1" parameter on the shortcode. Please, read details in the README.md 

It was implemented in https://github.com/OpenDevelopmentMekong/wpckan/commit/a8d20b20d280a5e74856ca5f9d13c146f162ffc8
