### ISSUE TITLE
Render list of extra fields on queries

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wpckan#74]
Currently the [wpckan_related_datasets] and [wpckan_query_datasets query="coal"] shortchodes return html contents containing the basic details of the datasets (title, description, license) and optionally the content of its resources.

Implementing a mechanism to return also the list of extra fields would increase the amount of information presented to the user. this feature should be optional tho.

**Comment by acorbi** [comment]
@chris-aeviator this is already implemented right? Has the code been integrated in the repo? If so, please close this issue

**Comment by kathi-aeviator** [comment]
Has been implemented. Close issue.
