### ISSUE TITLE
Add related dataset from CKAN in wordpress metabox errors

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wpckan#85]
The wpcank plugin errors, the suggested dataset is not listed on test site in the HTTPS server. 
Suggestion: the api url from http request should change to https  request,
http://data.opendevelopmentmekong.net/api/3/action/package_search?q=adb

![screenshot_1](https://cloud.githubusercontent.com/assets/6613530/8151565/56c54f74-133a-11e5-80df-58ec77994de0.jpg)

**Comment by acorbi** [comment]
@Huyeng Can you specify concrete steps to reproduce this error. I could add related datasets to topic pages normally.
Anyway, I have changed the CKAN url from http:// to https:// in http://opendevelopmentmekong.net/wp-admin/options-general.php?page=wpckan

**Comment by Huyeng** [comment]
I tested on the wordpress site under the https. You can test by adding the line to access the https:
119.81.30.162 www.opendevelopmentmekong.net opendevelopmentmekong.net 

BTW, when did you change the url, maybe I have not pulled the last changed. The last redeploy is on friday night.

**Comment by acorbi** [comment]
I changed the URL on the settings, so no code change involved. Can you please change the url yourself on https://opendevelopmentmekong.net/wp-admin/options-general.php?page=wpckan and seeing if the error still happens?

**Comment by acorbi** [comment]
@Huyeng have you tried changing the URL to https on https://opendevelopmentmekong.net/wp-admin/options-general.php?page=wpckan ? Does it fix the issue?

**Comment by acorbi** [comment]
Closing, this Issue has been solved once wordpress is accessed only via https
