### ISSUE TITLE
The related CKAN dataset on the topic pages disappeared

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wpckan#86]
@Alex, after deploying the script, the related dataset box on the topic page is not showing, please check.

**Comment by acorbi** [comment]
@Huyeng : Can you provide any link of the topic pages where it has disappeared? On this one it is working as expected http://opendevelopmentmekong.net/topics/environment-and-natural-resources/

**Comment by Huyeng** [comment]
The energy topic page, a number of related dataset are added through the metabox, but they won't be shown on the front-end of the page: http://opendevelopmentmekong.net/topics/energy/
![energy](https://cloud.githubusercontent.com/assets/6613530/8159946/c02634d2-1395-11e5-8830-e4b4f0f350ee.png)
![related-dataset](https://cloud.githubusercontent.com/assets/6613530/8159947/c02fec0c-1395-11e5-91c1-626e40e0295b.png)

**Comment by Huyeng** [comment]
The error may cause of the undifine dataset that added. I can't delete it either.

**Comment by acorbi** [comment]
@Huyeng I have checked and the related resources added do not exist in CKAN anymore. That might be the Issue. Even if the undefined dataset cannot be deleted, adding another one works.

@DBishton can you please coordinate a review of the related resources added to topic pages?

**Comment by acorbi** [comment]
Closing, this Issue relies on the editorial workflow
