### ISSUE TITLE
wpckan needs php-curl extension loaded

### ISSUE THREAD

**Issue by tremblaysimon** [OpenDevelopmentMekong/wpckan#88]
I think it should be a good idea to include php-curl as a requirement to be able to run wpckan extension. 

Also, to see explicitly the right error message in wpckan error log I think it should be nice to uncomment line https://github.com/OpenDevelopmentMekong/wpckan/blob/master/utils/wpckan_api.php#L420 to see that message in case we forget to enable php curl extension: ./wordpress/wp-content/plugins/wpckan/utils/wpckan_api.php | 421 ] ERROR API CALL on wpckan_api_ping message: The PHP cURL extension must be installed to use Guzzle.

**Comment by acorbi** [comment]
Thanks for your feedback @tremblaysimon, wil include this for release 1.2.0

**Comment by acorbi** [comment]
@tremblaysimon PHP cURL extension must be installed on the server so I have just included instructions on the README file.

As you suggested, I have uncommented those lines so the error gets logged.

Question: Are you using the plugin for any project? Can you share some infos about how you use it? 

Thanks
