### ISSUE TITLE
wpckan just returns 10 entries 

### ISSUE THREAD

**Issue by chris-aeviator** [OpenDevelopmentMekong/wpckan#96]
When importing laws on page-laws.php wpcan is only returning 10 results when implemented like in https://github.com/OpenDevelopmentMekong/opendev-wptheme/blob/master/functions.php#L1165

Please provide a fix to query for all available law records.

**Comment by acorbi** [comment]
@chris-aeviator there seems to be an issue with the CKAN API, if you specify a higher limit (e.g limit=1000) it returns all.... See https://github.com/OpenDevelopmentMekong/opendev-wptheme/blob/impl-342/functions.php#L1165  and read about hard limit of 1000 on http://docs.ckan.org/en/latest/api/index.html#ckan.logic.action.get.package_search

**Comment by acorbi** [comment]
Closing this, it is documented
